name: Create-Issue
on:
  issues:
    types: [ labeled ]
jobs:
  backport:
    runs-on: ubuntu-latest
    env:
      EVENT: ${{ toJson(github.event) }}
    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Test
      run: |
        echo "$EVENT"
        echo ${{ github.event.action }}
        echo ${{ github.event_name }}
        echo ${{ github.event.label.name }}
        python .github/workflows/create-issue.py "$EVENT" test