name: Create-Issue
on:
  issues:
    types: [ labeled ]
jobs:
  backport:
    runs-on: ubuntu-latest
    steps:
    - name: Test
      run: |
        echo ${{ github.event }}
        echo ${{ github.event_name }}
        echo ${{ github.event.label.name }}